apiVersion: apps/v1
kind: Deployment
metadata:
  name: ten-agent-demo
  namespace: ten-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ten-agent-demo
  template:
    metadata:
      labels:
        app: ten-agent-demo
    spec:
      containers:
        - env:
            - name: AGENT_SERVER_URL
              value: http://ten-agent-build-service:8080
          image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/dev/ten_agent_demo:latest # 替换你的镜像地址,部署palyground
          name: ten-agent-demo
          ports:
            - containerPort: 3000
          resources:
            requests:            
              cpu: "1"          
              memory: "2Gi"     
            limits:            
              cpu: "2"         
              memory: "4Gi"   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ten-agent-build
  namespace: ten-framework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ten-agent-build
  template:
    metadata:
      labels:
        app: ten-agent-build
    spec:
      containers:  
        - env:
            - name: LOG_PATH
              value: /tmp/ten_agent
            - name: LOG_STDOUT
              value: "true"
            - name: GRAPH_DESIGNER_SERVER_PORT
              value: "49483"
            - name: SERVER_PORT
              value: "8080"
            - name: WORKERS_MAX
              value: "100"
            - name: WORKER_QUIT_TIMEOUT_SECONDES
              value: "60"
            - name: AGORA_APP_ID
              value: {{AGORA_APP_ID}} # 替换你的 agora app id
            - name: AGORA_APP_CERTIFICATE
              value: {{AGORA_APP_CERTIFICATE}} # 替换你的 agora app certificate
            - name: agora_token
              value: {{agora_token}} # 替换你的 agora token
            - name: AWS_ACCESS_KEY_ID
              value: {{AWS_ACCESS_KEY_ID}} # 替换你的 aws access key id
            - name: AWS_SECRET_ACCESS_KEY
              value: {{AWS_SECRET_ACCESS_KEY}} # 替换你的 aws secret access key
            - name: OPENAI_API_BASE
              value: https://api.openai.com
            - name: OPENAI_API_KEY
              value: "" # 
            - name: OPENAI_MODEL
              value: gpt-4o-mini
            - name: OPENAI_VENDOR
              value: ""
            - name: OPENAI_AZURE_ENDPOINT
              value: ""
            - name: OPENAI_AZURE_API_VERSION
              value: ""
            - name: OPENAI_REALTIME_API_KEY
              value: ""
            - name: AZURE_OPENAI_REALTIME_API_KEY
              value: ""
            - name: AZURE_OPENAI_REALTIME_BASE_URI
              value: ""
            - name: OPENAI_PROXY_URL
              value: ""
            - name: QWEN_API_KEY
              value: ""
            - name: WEATHERAPI_API_KEY
              value: ""
            - name: BING_API_KEY
              value: ""
            - name: FIRESTORE_PROJECT_ID
              value: ""
            - name: FIRESTORE_PRIVATE_KEY_ID
              value: ""
            - name: FIRESTORE_PRIVATE_KEY
              value: ""
            - name: FIRESTORE_CLIENT_EMAIL
              value: ""
            - name: FIRESTORE_CLIENT_ID
              value: ""
            - name: FIRESTORE_CERT_URL
              value: ""
          image: xxxx.dkr.ecr.us-east-1.amazonaws.com/dev/ten_agent_build:latest # 替换你的镜像地址,部署agent
          name: ten-agent-build
          ports:
            - containerPort: 8080
          resources:
            requests:            
              cpu: "2"          
              memory: "4Gi"
            limits:            
              cpu: "3"         
              memory: "6Gi"