apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-test-app
  namespace: logs-collect
  labels:
    app: mq-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mq-test-app
  template:
    metadata:
      labels:
        app: mq-test-app
    spec:
      containers:
      - name: mq-test-app
        image: <your-account-id>.dkr.ecr.<region>.amazonaws.com/mq-test-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mq-test-app-service
  namespace: logs-collect
spec:
  selector:
    app: mq-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
